//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class NextOnServicesEntities3 : DbContext
{
    public NextOnServicesEntities3()
        : base("name=NextOnServicesEntities3")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<SupplierProject> SupplierProjects { get; set; }
    public DbSet<ProjectMappingg> ProjectMappinggs { get; set; }
    public DbSet<Project> Projects { get; set; }
    public DbSet<ProjectsUrl> ProjectsUrls { get; set; }
}
