//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Project
{
    public int ID { get; set; }
    public string PName { get; set; }
    public string Descriptions { get; set; }
    public Nullable<int> ClientID { get; set; }
    public string PID { get; set; }
    public string PManager { get; set; }
    public string LOI { get; set; }
    public string IRate { get; set; }
    public Nullable<double> CPI { get; set; }
    public Nullable<int> Status { get; set; }
    public string SampleSize { get; set; }
    public string Quota { get; set; }
    public string SDate { get; set; }
    public string EDate { get; set; }
    public string Country { get; set; }
    public Nullable<int> LType { get; set; }
    public string Notes { get; set; }
    public Nullable<System.DateTime> CreationDate { get; set; }
    public Nullable<int> IsActive { get; set; }
    public string BlockDevice { get; set; }
    public Nullable<int> IPCount { get; set; }
    public string ProjectIdFromAPI { get; set; }
    public string ProjectFrom { get; set; }
}

public partial class ProjectMappingg
{
    public int ID { get; set; }
    public Nullable<int> ProjectID { get; set; }
    public Nullable<int> CountryID { get; set; }
    public Nullable<int> SUpplierID { get; set; }
    public string OLink { get; set; }
    public Nullable<double> CPI { get; set; }
    public string MLink { get; set; }
    public string SID { get; set; }
    public string Code { get; set; }
    public string SCode { get; set; }
    public string NID { get; set; }
    public Nullable<int> IsUsed { get; set; }
    public string Status { get; set; }
    public string ClientIP { get; set; }
    public string ClientBrowser { get; set; }
    public Nullable<System.DateTime> CreationDate { get; set; }
    public Nullable<int> Respondants { get; set; }
    public Nullable<int> IsSent { get; set; }
    public string Notes { get; set; }
    public Nullable<int> IsChecked { get; set; }
    public string Completes { get; set; }
    public string Terminate { get; set; }
    public string Quotafull { get; set; }
    public string Screened { get; set; }
    public string Overquota { get; set; }
    public string Incomplete { get; set; }
    public string Security { get; set; }
    public string Fraud { get; set; }
    public string SUCCESS { get; set; }
    public string DEFAULT { get; set; }
    public string FAILURE { get; set; }
    public string QUALITY_TERMINATION { get; set; }
    public string OVER_QUOTA { get; set; }
    public Nullable<int> IsActive { get; set; }
    public Nullable<int> Block { get; set; }
    public Nullable<int> TrackingType { get; set; }
    public Nullable<int> Prescreening { get; set; }
    public Nullable<int> RC { get; set; }
    public Nullable<int> AddHashing { get; set; }
    public string ParameterName { get; set; }
    public string HashingType { get; set; }
}

public partial class ProjectsUrl
{
    public int ID { get; set; }
    public Nullable<int> PID { get; set; }
    public Nullable<int> CID { get; set; }
    public string Url { get; set; }
    public Nullable<System.DateTime> CreationDate { get; set; }
    public string Notes { get; set; }
    public Nullable<double> CPI { get; set; }
    public string Quota { get; set; }
    public Nullable<int> Status { get; set; }
    public Nullable<int> Token { get; set; }
    public string ParameterName { get; set; }
    public string ParameterValue { get; set; }
    public Nullable<int> ApplytoSupplier { get; set; }
    public string OriginalURL { get; set; }
    public Nullable<int> ApplyToSupplier1 { get; set; }
}

public partial class SupplierProject
{
    public int ID { get; set; }
    public string PMID { get; set; }
    public string SID { get; set; }
    public string UID { get; set; }
    public string Status { get; set; }
    public string ClientIP { get; set; }
    public string ClientBrowser { get; set; }
    public Nullable<int> IsSent { get; set; }
    public string Device { get; set; }
    public Nullable<System.DateTime> StartDate { get; set; }
    public Nullable<System.DateTime> EndDate { get; set; }
    public Nullable<System.DateTime> CreationDate { get; set; }
    public string ActStatus { get; set; }
    public string ENC { get; set; }
}
